### ISSUE TITLE
Add Sei to Station

### ISSUE THREAD

**Issue by besated** [terra-money/station-assets#9]
### What's the name of the chain?
Sei

### Is Sei a mainnet or a testnet?
testnet

### Great, now we need the Sei logo.
![Sei](https://www.seinetwork.io/logo.svg)

### What's the Sei testnet chain ID?
atlantic-1

### What's the URL to a public LCD?
https://sei-chain-incentivized.com/sei-chain-app/

### What are the IBC channels?
- From Terra: channel-100
- To Terra: channel-11

### What's the Bech32 address prefix?
sei

### Which coinType do you prefer to use for the bech32 address generation?
118

### What's the on-chain token?
usei

### What's the token name?
Sei

### What's the token symbol?
SEI

### What's the token logo?
![Sei](https://drive.google.com/file/d/1P4BfeXBVsrjTzGElDwPhrW9P0CsDTXdh/view)

### What's the minimum gas-price for Sei on Sei?
0.01

### What's your email?
bryan@seinetwork.io

### What's your Telegram?
besated

### Chain file:
```js
module.exports = {
  chainID: 'atlantic-1',
  lcd: 'https://sei-chain-incentivized.com/sei-chain-app/',
  gasAdjustment: 1.75,
  gasPrices: { usei: 0.01 },
  prefix: 'sei',
  coinType: '118',
  baseAsset: 'usei',
  name: 'Sei',
  icon: 'https://www.seinetwork.io/logo.svg',
  ibc: {
    fromTerra: 'channel-100',
    toTerra: 'channel-11',
  }
}
```

**Comment by ericHgorski** [comment]
PR #55
